#! zsh
if [[ -z $TASKRC ]]; then
	export TASKRC=$XDG_CONFIG_HOME/task/taskrc
fi
if [[ -z $TIMEWARRIORDB ]]; then
	export TIMEWARRIORDB=$XDG_DATA_HOME/timew
fi
if [[ -z $VIT_DIR ]]; then
	export VIT_DIR=$XDG_CONFIG_HOME/vit
fi
